### ISSUE TITLE
Some files not mentioned

### ISSUE THREAD

**Issue by zmoon** [Beliavsky/FortranTip#28]
I am working on some parsing of this repo's readme and file list to help automate FTB. I found some programs that are in the repo but not linked to in the index, and one program that is mentioned in the readme but not present in the repo:

Not mentioned:
- `2d_array.f90`
- `alloc.f90`
- `array_intrinsics.f90`
- `assoc.f90`
- `bitwise.f90`
- `bounds.f90`
- `char.f90`
- `count_pack.f90`
- `do_loop_index.f90`
- `elemental.f90`
- `func.f90`
- `function.f90`
- `hello_world.f90`
- `if.f90`
- `implicit_save.f90`
- `input_data.f90`
- `loop.f90`
- `merge.f90`
- `module.f90`
- `naming.txt`
- `one_line_if.f90`
- `operators.f90`
- `power.f90`
- `sections.f90`
- `shortest_code.f90`
- `sum_exit.f90`
- `trim.f90`

Mentioned in the readme but not present in the repo:
- `precision.f90`

**Comment by Beliavsky** [comment]
Thanks for pointing these out. I added precision.f90, and the link to it in the readme now works. I will look at whether the other codes have associated tweets.

**Comment by zmoon** [comment]
*Updated list*

Not mentioned in the readme:
- `bitwise.f90`
- `elemental.f90`
- `func.f90`
- `function.f90`
- `hello_world.f90`
- `if.f90`
- `implicit_save.f90`
- `input_data.f90`
- `loop.f90`
- `merge.f90`
- `module.f90`
- `naming.txt`
- `one_line_if.f90`
- `operators.f90`
- `power.f90`
- `sections.f90`
- `shortest_code.f90`
- `sum_exit.f90`
- `trim.f90`

**Comment by Beliavsky** [comment]
I went through the list and added links to codes in the readme. In a few cases I wrote a code and uploaded it but decided I would not write a tweet about it.

**Comment by zmoon** [comment]
Ok, sounds good. Feel free to close this issue if you are satisfied.

Here is the updated list for the record:

Not mentioned in the readme:
- `bitwise.f90`
- `input_data.f90`
- `naming.txt`
- `operators.f90`
- `shortest_code.f90`
- `trim.f90`
